### ISSUE TITLE
hero learn more

### ISSUE THREAD

**Issue by jakedex** [dawnlabs/next-site#3]
"learn more" button should link to "push your site to the edge" section

**Comment by mfix22** [comment]
@jake we need some CTA that points to `/learn/excel/static-html-export`? Maybe the other learn button?

**Comment by jakedex** [comment]
Hmm, it didn't sound that important to Tim... and imo having something like they do with the "learn more" CTA on https://zeit.co makes more sense here. But idk, what do you guys think?

**Comment by briandennis** [comment]
I agree that it makes more sense to have the CTA at the top scroll down the page rather than bring you to the learn documentation. I think @jakedex is right that it didn't sound very important to Tim. Plus it's easy to swap out later.

Can we point to `/learn/excel/static-html-export` somewhere else?

**Comment by mfix22** [comment]
> Can we point to /learn/excel/static-html-export somewhere else?

Yeah that's what i meant. just point to there from another part of the page? Like one of the other buttons

**Comment by jakedex** [comment]
"Powerful Features, Out of the Box" button and "Dead Simple" button should link there
